version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcurl
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    volumes:
      - ./backend/api:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_DATABASE_HOST=postgres
      - DJANGO_DATABASE_NAME=nextcurl
      - DJANGO_DATABASE_USER=user
      - DJANGO_DATABASE_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcurl
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
    depends_on:
      - postgres

  migration:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    command: python manage.py migrate
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_DATABASE_HOST=postgres
      - DJANGO_DATABASE_NAME=nextcurl
      - DJANGO_DATABASE_USER=user
      - DJANGO_DATABASE_PASSWORD=password
    depends_on:
      - postgres

  realtime:
    build:
      context: ./backend/realtime
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  ai:
    build:
      context: ./backend/ai_vr
      dockerfile: Dockerfile.ai
    ports:
      - "5000:5000"

  vr:
    build:
      context: ./backend/ai_vr
      dockerfile: Dockerfile.vr
    ports:
      - "5001:5001"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
