# Generated by Django 4.2.19 on 2025-02-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="total_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_accessed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="progress",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("watched_duration", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("last_watched", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="courses.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("lesson", "student")},
            },
        ),
    ]
